#!/usr/bin/env python
# coding: utf-8

# In[45]:


from bs4 import BeautifulSoup
import requests


# In[46]:


page=requests.get("http://scores.sify.com/live-cricket-scores/ICC-Cricket-World-Cup-2019/AUSTRALIA_vs_WEST-INDIES_JUN06_2019.shtml")
page


# In[47]:


#page.content


# In[48]:


soup=BeautifulSoup(page.content,'html.parser')


# In[49]:


print(soup.prettify())


# In[50]:


ss=soup.find('div',class_='col-md-6')
my_table=ss.find(class_='table table-hover batting')


# In[51]:


my_table.find_all('th')


# In[52]:


links=my_table.find_all('a')
links


# In[53]:


Batsman=[]
for i in links:
    Batsman.append(i.get_text())
print(Batsman)


# In[54]:


rows=my_table.find_all('tr')


# In[55]:


table_body=soup.find('tbody')
rows = table_body.find_all('tr')
for row in rows[0:-2]:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    print(cols)


# In[38]:


R=[]
for row in rows[0:-2]:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    R.append(cols[2])


# In[39]:


R


# In[40]:


B=[]
for row in rows[0:-2]:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    B.append(cols[3])


# In[41]:


B


# In[43]:


Fours=[]
for row in rows[0:-2]:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    Fours.append(cols[4])


# In[44]:


Fours


# In[56]:


Sixes=[]
for row in rows[0:-2]:
    cols=row.find_all('td')
    cols=[x.text.strip() for x in cols]
    Sixes.append(cols[5])


# In[57]:


Sixes


# In[60]:


import pandas as pd 
ScoreBoard=pd.DataFrame({
    "Batsman":Batsman,
    "Runs":R,
    "Balls":B,
    "4s":Fours,
    "6s":Sixes
})
ScoreBoard


# In[ ]:




